### ISSUE TITLE
Hello! You work is great! How I can use in vue 3?

### ISSUE THREAD

**Issue by devheniik** [giordanna/vue2-leaflet-routing-machine#4]

**Comment by giordanna** [comment]
Hi!
Unfortunately I haven't maintained this repo for a long while, and also the creator of [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) also barely maintains the plugin :( and the vue2-leaflet alternative for vue3, [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet), right now is in beta version and unstable.

I tried using both packages but I ran into errors. For now the most stable solution is using [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) and [leaflet](https://github.com/Leaflet/Leaflet) on a Vue 3 project.

Here's an example:
https://codesandbox.io/s/vue-3-leafleft-routing-machine-ujyscz?file=/src/components/LRoutingMachine.vue

Note that it is missing the marker's image.

**Comment by devheniik** [comment]
> Hi!
> Unfortunately I haven't maintained this repo for a long while, and also the creator of [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) also barely maintains the plugin :( and the vue2-leaflet alternative for vue3, [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet), right now is in beta version and unstable.
> 
> I tried using both packages but I ran into errors. For now the most stable solution is using [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) and [leaflet](https://github.com/Leaflet/Leaflet) on a Vue 3 project.
> 
> Here's an example:
> https://codesandbox.io/s/vue-3-leafleft-routing-machine-ujyscz?file=/src/components/LRoutingMachine.vue
> 
> Note that it is missing the marker's image.

**Thanks, l love you!**

**Comment by UnLegitCombos** [comment]
Hi, I started a project and decided to use vue-leaflet, I'm probably too deep to revert to doing it another way, is there any way to make it work using vue-leaflet? I have been trying for a couple of days now.

**Comment by Recly** [comment]
Hello! You can take a look at my solution: https://github.com/Recly/vue3-leaflet-routing-machine
